Business Problem: Predicting House Prices

The provided dataset presents a business problem in the real estate domain: predicting house prices based on the area of the property. Each row in the dataset represents a house, with its corresponding price and area. The objective here is to develop a predictive model that can accurately estimate house prices based on the given area. This problem is crucial for real estate companies, as it enables them to determine fair and competitive prices for properties, assist clients in making informed decisions, and optimize their overall business strategies. By accurately predicting house prices, real estate companies can enhance customer satisfaction, attract more clients, and improve their profitability in a dynamic and competitive market.






Without Pre-Processing

In [497]:
import pandas as pd

In [498]:
df = pd.read_csv("Housing.csv")

In [499]:
df

price   area
0   13300000   7420
1   12250000   8960
2   12250000   9960
3   12215000   7500
4   11410000   7420
5   10850000   7500
6   10150000   8580
7   10150000  16200
8    9870000   8100
9    9800000   5750
10   9800000  13200
11   9681000   6000
12   9310000   6550
13   9240000   3500

In [500]:
X = df.iloc[:,1].values
y = df.iloc[:,0].values

X

array([ 7420,  8960,  9960,  7500,  7420,  7500,  8580, 16200,  8100,
        5750, 13200,  6000,  6550,  3500], dtype=int64)

In [501]:
y

array([13300000, 12250000, 12250000, 12215000, 11410000, 10850000,
       10150000, 10150000,  9870000,  9800000,  9800000,  9681000,
        9310000,  9240000], dtype=int64)

In [503]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 0)

In [504]:
import numpy as np
from sklearn.linear_model import LinearRegression
X_train = X_train.reshape(-1, 1)
y_train = y_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)


In [505]:
y_pred

array([[10791686.78609385],
       [10810865.20743817],
       [10764517.35585606]])

In [506]:
y_test

array([ 9870000, 10150000, 11410000], dtype=int64)